### ISSUE TITLE
Rspamd not found in transaction.results since 1.3.0

### ISSUE THREAD

**Issue by DoobleD** [haraka/haraka-plugin-rspamd#34]
### system info

Please report your OS, Node version, and Haraka version by running this shell script on your Haraka server and replacing this section with the output.

echo "Haraka | $(haraka -v)"; echo " --- | :--- "; echo "Node | $(node -v)"; echo "OS | $(uname -a)"; echo "openssl | $(openssl version)"

```
Haraka | Haraka.js — Version: 3.0.1
 --- | :--- 
Node | v14.21.3
OS | Linux <redacted> 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 GNU/Linux
openssl | OpenSSL 1.1.1n  15 Mar 2022
```

### Expected behavior

`connection.transaction.results.get('rspamd')` should be defined.

### Observed behavior

`connection.transaction.results.get('rspamd')` is not defined.

### Steps to reproduce

This happens for me since 1.3.0. The rspamd transaction result isn't defined, for instance in the watch plugin and in our own plugins.

```
DEBUG] [-] [watch]  skip="rspamd not found"
```

Reverting to 1.2.0 resolves the issue. I tried tracking down the exact issue and suprisngly it's because of the change from a `forEach` to a `for of` in `get_clean`:

https://github.com/haraka/haraka-plugin-rspamd/commit/37d906757e66ae0b9d70380c1f431d5a727c00cf#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346L383-R396

Specifically, it seems that the `if (data[b].length)` inside the loop returns more often since the change. It's unclear to me why this change affects anything, as far as I know it should be identical.

**Comment by nishils** [comment]
This is a bug that I also ran into. The root cause here is pretty subtle.

A `return` in a `forEach` loop goes to the next iteration. A `return` in a `for` loop exits out of the function entirely. This is a major bug in 1.3.0 and should be patched. I'll see if I can get a PR up soon to help with this.

**Comment by msimerson** [comment]
Thanks @nishils, that was exactly correct. I missed updating those.
